### ISSUE TITLE
Persistent apps with Docker Platform

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#110]

**Comment by jonasrosland** [comment]
Title:
Persistent applications on the Docker platform

Abstract:
Much of today's focus when it comes to containers is around stateless applications, scaling them from 1 to infinity and rescheduling them automatically when something goes wrong. But what about the data that they create? How can we create scalable data persistence backends for our services to make sure our stored data is highly available?

In this session we'll do live demos of both stateless and stateful applications running on the Docker platform, with focus on persistence layers like caching engines and databases, all stored on highly available distributed storage platforms.

Outline:
Difference between stateless and stateful applications
Go through the Docker volume functionality
Show live demos of how to run stateful applications and how you can enable advanced functionality for testing applications against live data without risk

Key takeaways:
Learn how to properly use Docker volume functionality
Stop being afraid of putting data services into containers

Keywords:
Docker volume
Storage
Advanced functionality
