### ISSUE TITLE
Live migration of containers

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#118]
We saw one at dockercon EU but the storage aspect of moving a container between hosts was handled via scp.. our volume functionality is the lock to making this work

**Comment by codenrhoden** [comment]
I didn't really see anything to that effect in https://youtu.be/dUixUP2lKeE?list=PLkA60AVN3hh87OoVra6MHf2L4UR9xwJkv.

I think you are talking about the optional filesystem copy that p.haul can do?

It does seem like a great story - showing how easily containers with attached volumes can be migrated when using REX-Ray. But, is the live-migration tooling actually in place? It doesn't seem so.
