### ISSUE TITLE
Cinder and Docker

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#120]
How are Openstack and Docker complimentary? What role does Cinder play for containers that need persistence? What role does Docker play for Openstack since it really needs thinks to be ephemeral?

**Comment by mux23** [comment]
Abstract: On the surface, it almost seems like OpenStack and Docker went toe-to-toe, and that Docker won a resounding victory. Under the covers however they address very different needs, and the two technologies are actually quite complementary. OpenStack's 'Cinder' block storage provider is an ideal method for provisioning storage to a clustered container engine, and in this presentation we'll discuss the whys and hows of using Cinder to provide storage persistence for containerized applications.

Outline: 
- Introduction
- OpenStack and Cinder overview
- OpenStack in a containerized world
- Cinder as a flexible storage provider
- Persistent storage - why and how
- Putting it all together
- Demo of Cinder-provisioned persistent storage for Docker containers
- Q&A

Takeaways: Attendees will leave with a better understanding of the fact that OpenStack and Docker are not actually competing, but are rather complementary, a few new thoughts about storage persistence, and some ideas on when and how to use OpenStack as resource-provisioning system in a containerized world.
