### ISSUE TITLE
Persistent Storage for Containers Using Cinder

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#26]

**Comment by clintkitson** [comment]
Persistent Apps in Containers on OpenStack

**Comment by clintkitson** [comment]
@jonasrosland You interested in this one?  Maybe it would turn into something re Mesos and persistent apps on OS.

**Comment by jonasrosland** [comment]
OpenStack is not my strong suit, I would recommend @drumulonimbus for this.

**Comment by mux23** [comment]
I can give this a shot.

**Comment by mux23** [comment]
Title: Persistent Storage for Containers using Cinder and REX-Ray

Abstract: Everyone loves containers, but nobody wants to talk about the elephant in the room - how can you make storage persist when the whole point of containers is that they have short lifespans? In this presentation we'll discuss how to use the REX-Ray volume driver, backed by Cinder, to provide persistent, preemptable storage to Docker.

**Comment by stephcarlson** [comment]
What about a fun/creative title: The Elephant in the Container Room.

**Comment by amandakatona** [comment]
@drumulonimbus Morning! will you please take a look at the title and then submit to OpenStack Summit CFP (preferably without the use of our project in the name)? Once it's submitted, please add the label as "submitted" and copy/paste the submitted abstract in here in case we want to use it later. Still going through the process on my end :) Thanks!

https://www.openstack.org/summit-login/login?BackURL=%2Fsummit%2Faustin-2016%2Fcall-for-speakers%2F

**Comment by mux23** [comment]
final abstract: Everyone loves containers, but nobody wants to talk about the elephant in the room - how can you make storage persist when the whole point of containers is that they have short lifespans? In this presentation we'll discuss how to use the REX-Ray volume driver, backed by Cinder, to provide persistent, preemptable storage to Docker container servers hosted on OpenStack.
