### ISSUE TITLE
RR and Magnum

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#27]

**Comment by clintkitson** [comment]
@codenrhoden If you're interested maybe some brief investigation on this one to see if it's viable?

**Comment by codenrhoden** [comment]
@clintonskitson yep! definitely on my list to do just that.

**Comment by clintkitson** [comment]
@codenrhoden FYI check this out https://review.openstack.org/#/c/265057/

**Comment by codenrhoden** [comment]
@clintonskitson As we discussed earlier in the week, the current state of Magnum when it comes to external storage is "working on it for the next release".  There is no support for Docker volume drivers, or for passing in custom volume parameters a la `docker run -v`.  So I picture the talk addressing why you want to do so, what the current state of the work in Mitaka is, and also can we make some simple tweaks to the Liberty codebase to actually make it happen today.  :)  Draft pasted in next comment.

**Comment by codenrhoden** [comment]
**Title:** Persistent Storage in Containers with Magnum, Why and How to Do it Today

**Abstract:**
Magnum presents an easy way to deploy a Container Orchestration Engine on top of your OpenStack cluster. However, in the Liberty release there is not yet a way to natively attach persistent storage volumes to your containers.  We'll take a look at the use cases for wanting to attach persistent storage to your containers, and look at some projects that integrate with Docker and Mesos to make volume management with containers easier.

We will also see if we can bring persistent storage capabilities to Magnum with current Docker volume drivers, and take a look at the work that is happening for Mitaka to make this capability native.

**Problem or Use Case:**
While containers started out being seen as ephemeral in nature when it comes to storage, there are many use cases where persistent storage is beneficial or required:
    • Running a replicated database with multiple nodes 
    • rescheduling failed containers
    • migrating containers between hosts

With the introduction of volume drivers in Docker 1.8, and even greater volume support in 1.9, projects like REX-Ray and Flocker present ways for the Docker Engine to attach storage from Cinder or other external storage providers directly to containers when they are started.
This session looks at the need for these projects, and why Magnum support for them is critical to real-world workloads.

**What should attendees learn:**
Attendees will learn about the new possibilities and problems that can be solved with containers when persistent storage is available to them.  They will learn about the capabilities of Magnum as it pertains to storage, and will come away with a better understanding of why adding support for volume drivers is critical.

**Why should this be selected:**
This session will expand users' and operators' understanding of what is possible with containers, and how to take advantage of persistent storage that is already being provided by Cinder.

**Comment by clintkitson** [comment]
nice

**Comment by stephcarlson** [comment]
Instead of the word should "Attendees should learn" use the word "will" - should is considered a wishy washy word.

**Comment by codenrhoden** [comment]
Thanks @stephcarlson!  Updated.

**Comment by amandakatona** [comment]
@codenrhoden Will you please submit to OpenStack Summit CFP? Once it's submitted will you please add the label "submitted"? Still learning the process over here! It would also be helpful if you copy/pasted the submitted abstract in here in case we want to use it later. Thanks!

https://www.openstack.org/summit-login/login?BackURL=%2Fsummit%2Faustin-2016%2Fcall-for-speakers%2F

**Comment by codenrhoden** [comment]
Submitted!
