### ISSUE TITLE
Docker Machine and OpenStack with RR

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#28]

**Comment by clintkitson** [comment]
Figuring this is up your alley @kacole2

**Comment by kacole2** [comment]
What's OpenStack? 😉

**Comment by kacole2** [comment]
Title: Automating a Persistent Container Infrastructure

Abstract: Containers have swelled with popularity and, in conjunction, the need for making containers persist state grows. If an application can be "dockerized" to persist state, it removes the need for apps to become 12-Factor or "Cloud Native". Allowing organizations to harness this new kind of infrastructure.

Docker Machine has created the simple deployment of a "Docker-ready" infrastructure on Nova. The next challenge is making the containers access storage from Cinder to persist state. Using the Docker Volume Driver Plugin, external storage can be utilized to offload data from the container to a storage end-point. REX-Ray, an Open Source project, is compatible with Cinder which means it's available for every OpenStack deployment that exists.
