### ISSUE TITLE
RackHD and OpenStack

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#31]

**Comment by kacole2** [comment]
Title: PXE Booting Your OpenStack Cloud

Abstract: We began using DevStack and running everything in virtual machines. Eventually, we graduate to running bare metal OpenStack. Have you thought about automating the entire roll-out?

Using RackHD, an open source configuration management and orchestration tool, we can create recipes for PXE booting our way to an automated infrastructure. RackHD enables you to load OpenStack services during an operating system roll out as well as completely configuring the environment.
