### ISSUE TITLE
Docker, Mesos, OpenStack, and REX-Ray

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#32]

**Comment by clintkitson** [comment]
@dvonthenen What do you think?

**Comment by davidvonthenen** [comment]
@clintonskitson Sounds interesting... Will come up with something for a proposal.

**Comment by davidvonthenen** [comment]
I submitted this a while back.
https://github.com/dvonthenen/proposals/blob/master/2016_OPENSTACK_US/Docker_Mesos_StoragePresistence.md
