### ISSUE TITLE
ScaleIO, Heat, and REX-Ray

### ISSUE THREAD

**Issue by clintonskitson** [emccode/conferences#33]
Why would someone deploy ScaleIO alongside OpenStack and leverage in guest SIO drivers to take care of data plane versus Cinder?

**Comment by clintkitson** [comment]
Title: Deploy and Operate ScaleIO with Openstack Heat
Description: Choosing the right platform for providing storage to Openstack platforms is important.  The right platform should be agile in how it is operated and configured.  ScaleIO is the perfect platform as it can be operated using Openstack tools and has many options for consuming at the guest level.  This session will involve live demos and discuss the different options that ScaleIO provides with different workloads in Openstack.

**Comment by amandakatona** [comment]
Hey Clint, is this abstract being updated based on your experience comments on #30 of talks not being selected that are too product focused? Should we add in more words such as "we found" or something to that effect so it doesn't come across as a product marketing pitch?

**Comment by clintkitson** [comment]
We can close this one out.. redundant to Adrian's
