### ISSUE TITLE
Heat and Cloud Formation Lessons Learned

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#35]

**Comment by mux23** [comment]
Title: Heat and CloudFormation Compatibility, or Lack Thereof

Abstract: A common perception of OpenStack Heat is that it provides compatibility with AWS CloudFormation, allowing you to build orchestration templates that can deploy cloud-native applications on both public and private clouds. The reality, we've found, is a little more complicated than that.

In this session we'll discuss the some gotchas we ran into when attempting to deploy an application on OpenStack Liberty, RackSpace Public Cloud, and Amazon AWS. We'll cover the major differences between the three platforms, and close with a series of take-away tips on how to build templates that bring cross-cloud orchestration closer to reality.

**Comment by stephcarlson** [comment]
In the second paragraph remove the word "the" before some gotchas. Next sentence We'll "also" cover... and then make "take-aways" plural and remove the word "tips."
