### ISSUE TITLE
Mesos Resource Provider Frameworks

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#41]

**Comment by cantbewong** [comment]
Submitted

Title:
A Resource Provider Framework to extend the capability of Mesos

Description:
Mesos is a popular platform for managing data center resources and workloads. Recently enhancements to Mesos extend its management scope to go beyond resources supplied by individual cluster nodes. For example Mesos can manage external storage such as AWS EBS volumes. Architecture and use of a Mesos external storage Framework will be described. 

Abstract: 
Mesos emerged from work at Twitter and UC Berkeley to become one of the most popular platforms for managing data center resources and workloads.
New extensions have been added to enable Mesos to extend beyond managing just the resources contained within individual cluster nodes. 

This talk will cover the design and usage of a Mesos Framework that can manage external storage resources. For example, this framework can manage global AWS EBS volumes that can be mounted and shared across cluster nodes. This enables more efficient, automated management of highly available workloads such as databases. It will also support Docker containers that utilize volumes on external storage.

The techniques demonstrated could be applied to configuration and allocation of other external resource types, for example a Mesos Framework could be developed to manage external network resources such as VLANs or subnets.

Takeaway for audience
New facilities are available in Mesos to extend existing installations, or to allow new deployments to use Mesos cluster management for formerly difficult workloads like databases. The same technique, of building an external resource manager could be applied to other global resources, such as network creation and allocation.
