### ISSUE TITLE
All About Mesosphere 

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#46]

**Comment by davidvonthenen** [comment]
@clintonskitson Not sure what you are looking for here... did you want me to talk about the Mesosphere the company? Or if it is just a general talk about Mesos, how is this different than the Mesos 101 (https://github.com/emccode/conferences/issues/56) proposal?

**Comment by clintkitson** [comment]
@dvonthenen Focuses on the commercially supported version of Mesosphere.. modules they bring that enterprise's expect.

**Comment by davidvonthenen** [comment]
@clintonskitson gotcha!

**Comment by davidvonthenen** [comment]
Description:
Introduction to Mesosphere, the commercially packaged product of the Apache Mesos with enterprise-level support. Discuss the product offering by taking a look at the ease of launching new workloads from their catalog of 40+ applications, support for Docker workloads, and deploying applications on their command line and web interface. Mesosphere enables hybrid cloud with the convenience of auto-scaling application and make your workload more elastic in the cloud. Demonstrate auto-scaling a simple web application to meet the demands of your growing business.

**Comment by davidvonthenen** [comment]
I believe this proposal supersedes this one:
https://github.com/emccode/EMCW2016/issues/8

**Comment by davidvonthenen** [comment]
@clintonskitson Just trying to make sure that things don't fall through the cracks. It looks like you reopen this issue, what exactly is the action item for this issue?

**Comment by davidvonthenen** [comment]
Closing out EMCW issues
