### ISSUE TITLE
Neutrino, REX-Ray, and Docker

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#47]

**Comment by codenrhoden** [comment]
Title: Leverage REX-Ray for persistent volumes in Neutrino and Docker

Abstract: Creating and mounting volumes in Virtual Machines and Containers can be done in a myriad of ways, and seems to be different for every underlying technology.  What if there was a consistent approach to volume management across IaaS and Container runtimes?  Well there is! In this session, we will show how REX-Ray can be used in both Neutrino and Docker to simplify and unify the steps to manage your volumes.

**Comment by codenrhoden** [comment]
Title: Use Neutrino today for VMs while preparing for a container world tomorrow

Abstract: Deploying and managing an OpenStack cluster is hard. Neutrino makes it easy, and paves the way for a world beyond VMs. OpenStack already has facilities for volume management, including attaching persistent storage. Are we done? Not if you want to future-proof your application for the move to containers.  We will look at how to leverage REX-Ray as a consistent interface to block storage that works with OpenStack, public cloud providers, and a multitude of container runtimes and schedulers.
