### ISSUE TITLE
Storage and Config Mgmt

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#49]

**Comment by codenrhoden** [comment]
Title: How Configuration Management Tools Make Your Storage Life Easier

Abstract: You shouldn't be managing any of your infrastructure by hand, and that includes your storage. In this session we look at how configuration management tools like Puppet and Ansible can be used to manage storage. For demos, we will look at two examples: (1) installing a ScaleIO cluster; (2) Setting up a multi-node Docker deployment in AWS and use REX-Ray for persistent volume management.
