### ISSUE TITLE
CloudFoundry and service brokers

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#50]

**Comment by clintkitson** [comment]
spoke to @spiegela about it

**Comment by clintkitson** [comment]
Title: Deliver ECS object services to Cloud Foundry applications
Description: Your applications likely need some form of object storage for their applications.  The overhead in plumbing this tends to be painful for most use cases.  Cloud Foundry has a service broker framework that enables external platforms to offer services, and enables the automated configuration for these services when requested.  Here we will cover the ECS and Could Foundry integration to seamlessly provide object services to applications.

**Comment by spiegela** [comment]
Cool.  I was going to write this up tonight.  Anything you'd like me to add to the abstract?  I can plan on doing a demo as part of the session as well.

**Comment by clintkitson** [comment]
Feel free to submit this through the CFP channels in whatever verbiage you want.  I will be passing the buck =)

**Comment by spiegela** [comment]
Submitted.  Now, we'll see if it's accepted.
