### ISSUE TITLE
Cassandra, ScaleIO, and Containers

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#52]

**Comment by jonasrosland** [comment]
Summary:
So you heard that Cassandra is the new hot database that all the cool kids are using, but what is it and why is it better than MSSQL? What kind of apps use it? And how do you run it and store all the data?
Let us show you how you can use Cassandra with new and modern apps, and how to run it on modern  infrastructures leveraging ScaleIO and Docker containers.
