### ISSUE TITLE
Container Schedulers 101 

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#54]

**Comment by cantbewong** [comment]
Title: A guided tour of container schedulers
Abstract:
There are now three leading open source platforms for running and managing conatainerized workloads: Docker Swarm, Kubernetes, and Mesos.  How do you decide which one makes sense for your project  This session will cover the strengths of each platform to help you decide which one makes sense for your environment.

**Comment by cantbewong** [comment]
Proposed title change: Choosing the right scheduler/manager for for container workloads

**Comment by cantbewong** [comment]
Suggested title change: A guided tour of container manager/schedulers
