### ISSUE TITLE
Immutable Infrastructure 101 

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#57]

**Comment by jonasrosland** [comment]
Summary:
No more artisanally hand-crafted infrastructures! Ban snowflake servers!
Immutable means "unchanging over time or unable to be changed", which is great if you work in operations. Stable, predictable, but of course you will have to make changes every now and then. How do you handle changes to your infrastructure without it impacting reliability, and how can you make sure the task is properly propagated over every part of the infrastructure that needs it?
Handling immutable infrastructures have become much easier now with modern tools and we will show live demos of a few such as Vagrant, Terraform and Ansible.
