### ISSUE TITLE
Containers are not Cloud Native

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#60]

**Comment by mux23** [comment]
Abstract: Containers are a hot ticket in 2016, and everyone seems to want to throw around the 'Cloud Native' buzzwords - but despite a common perception, those two technologies are not joined at the hip! In this talk we'll cover what makes an application 'Cloud Native' (hint: not necessarily containers), and we'll talk about building applications with containers (hint: not necessarily Cloud Native).
