### ISSUE TITLE
Cloud Native Infrastructure for your Apps

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#61]

**Comment by jonasrosland** [comment]
Summary:
How do you deal with infrastructure resiliency when your modern apps are mostly stateless? Do you care at all if your infrastructure goes down? Of course you do!
In this session will explain and show live demonstrations of several concepts such as stateless vs stateful applications and how to build proper Cloud Native Infrastructure for them, data persistence in distributed environments, service discovery and orchestration layers.
