### ISSUE TITLE
Unstructured and Structured PaaS Demystified

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#64]

**Comment by jonasrosland** [comment]
Summary:
It's the age-old tale of building vs buying, but with a twist. Almost all of the tools to build your own PaaS today are Open Source, so why wouldn't you want to build your own? The unstructured vs structured discussion is very opinionated right now and in this session we will go through the pros and cons of both, with explanations of standard concepts such as distributed systems, containers and orchestration engines.
