### ISSUE TITLE
State of container eco-system with storage persistence

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#67]

**Comment by cantbewong** [comment]
Abstract:
First generation hosting platforms for containers assumed that the workload inside the container would be stateless and ephemeral. But, most useful systems requires storage of state somewhere. 
It used to be the case that the "somewhere" had to be outside a container.  With evolution of container platforms such as Docker and Mesos, you can now run stateful applications such as databases inside a container.  This session will cover the current state of persistent storage, containers, and schedulers, including future directions in this arena.

**Comment by cantbewong** [comment]
deck: http://www.slideshare.net/EMCCODE/emc-world-2016-code13-state-of-the-container-ecosystem-with-persistent-applications

demo video: https://www.youtube.com/watch?v=lLUAK4RyXp8&list=PLbssOJyyvHuWiBQAg9EFWH570timj2fxt&index=3
