### ISSUE TITLE
Build Your Brand: Lessons On How To Grow Your Marketability and Value In Tech

### ISSUE THREAD

**Issue by kacole2** [emccode/conferences#73]
Abstract: There are ways of survival in the tech industry. Staying on top of industry trends, networking with peers, and being social are a few ways our team has succeeded. Listen to members of the {code} team talk on a panel of how they transformed their careers and became a part of a small group creating enormous change in a large company.

**Comment by stephcarlson** [comment]
Kenny, this is a wonderful topic! I think this should be also used to submit to other talks if you haven't already!
