### ISSUE TITLE
Symbiosis with Open Source and my business

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#77]

**Comment by clintkitson** [comment]
Description: Recognizing that times are changing for how software that has a positive impact on a bottom line is developed is critical.  Having a healthy Open Source strategy is both important for your business and the OSS community.  Learn from the pros and and hear about some simple steps that will take you from zero to hero and enable your business to thrive in Open Source.

**Comment by kacole2** [comment]
http://www.slideshare.net/EMCCODE/emc-world-2016-cnaitl01-adopting-an-open-source-strategy
