### ISSUE TITLE
Contributing to large open source projects

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#78]

**Comment by codenrhoden** [comment]
Title: Intimidate Me Not - how to contribute to large open source projects
Abstract: The open source community at large is a fast-paced environment where enhancements and bug fixes can be contributed by anyone.  However, it can be intimidating when trying to contribute to a large project that has their own policies and procedures for accepting changes.  In this session we will share EMC {code}'s best strategies and advice for getting your changes accepted into that OSS project you've been lurking around!

**Comment by clintkitson** [comment]
nice
