### ISSUE TITLE
Moving to modern collaboration tools

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#79]

**Comment by clintkitson** [comment]
Title: Hijack Your Collaboration Toolset and Jumpstart Your Open Source Presence
Description: Building a great open source strategy starts from the inside.  Those that do the best at it focus on real-time communication, open and collaborative discussions, and tend to be more successful with their open source initiatives and even hiring the right talent.  Learn about the tools that can help align your company to open source with external facing toolsets.

**Comment by mux23** [comment]
Abstract: The dawn of email and instant messaging enabled teams to be distributed across the world and still work together effectively; source-control systems like CVS and Subversion made it possible for teams to work on the same source code. Those technologies are now old enough to vote! This session will cover the current state of online collaboration tools, strategies to enable your team communications, and ideas to help future-proof your technology decisions.
