### ISSUE TITLE
DevHigh5 with EMC {code}

### ISSUE THREAD

**Issue by kacole2** [emccode/conferences#81]
Abstract: Within the past year, the EMC {code} GitHub page has amassed a bunch of projects through the DevHigh5 program. The session will cover what the DevHigh5 program is and an overview of projects submitted through DevHigh5. This session will showcase upwards of 15 tools that integrate with varying EMC products. Learn about all the things you never even knew existed!

**Comment by clintkitson** [comment]
yup
