### ISSUE TITLE
Sprinkle Pixie Dust: Take Your Internal Projects from Ho Hum to Interactive

### ISSUE THREAD

**Issue by kacole2** [emccode/conferences#82]
Abstract: Every year we are tasked with a laundry list of projects to accomplish. New server roll-outs, new applications coming on-board, and more. How are your projects being tracked? What tools are you using to make everyone's life easier? I hope it's not Excel. Learn how to use collaborative tools such as Scrum and Kanban to track processes and make it interactive for everyone to be a part of it!

PS... i hate this idea... i'm just spitballing ideas...

**Comment by clintkitson** [comment]
similar topic here https://github.com/emccode/conferences/issues/79
