### ISSUE TITLE
*Your Company* {code}: Flip Your Company Upside Down With A Tiger Team 

### ISSUE THREAD

**Issue by kacole2** [emccode/conferences#83]
Abstract: EMC {code} has been seen as a tremendous success from many angles, such as executive sponsorship and community engagement. This session will cover the birth of {code} and how our mission is creating a positive impact for EMC. New ways of thinking, providing resources for learning, and contributing value in open-source technology are some of the things {code} provides to EMC. Learn all about EMC {code}'s successes and failures within a 1 year time frame to see if your organization can benefit from creating their own {code} initiative.

**Comment by clintkitson** [comment]
I like it
