### ISSUE TITLE
Open Source. The Rise of Every Great Thing

### ISSUE THREAD

**Issue by kacole2** [emccode/conferences#88]
On February 4th, 2004. Mark Zuckerberg along with his Harvard roommates changed the face of history. The launch of thefacebook.com would prove to be the start of something unreal, something profound and something of great ordeal that would lead to a $33 Billion dollar evaluation. But how did they do it? The phrase most commonly used is that "we stand on the shoulders of giants". Learn about the history of open source software and how the rate of innovation has drastically increased in the past 10 years. Listen to the {code} team talk about how Open Source is changing the next generation of infrastructure and what it means to the future of EMC.

**Comment by kacole2** [comment]
cc @stephcarlson

**Comment by stephcarlson** [comment]
I like it @kacole2! Including @Amandakatona!

**Comment by kacole2** [comment]
fixed spelling mistakes
