### ISSUE TITLE
Standardizing the Go Build Process with Gomk

### ISSUE THREAD

**Issue by akutz** [emccode/conferences#89]
## Type

Tutorial
## Abstract

Managing the build process for a Go project often results in a confusing solution supported by disparate & duplicate tools, or worse, orthogonal build systems that replace Go's native tools instead of working with them.

[Gomk](https://github.com/akutz/gomk) aims to be the standard solution for the Go build process by working **with** the standard Go build tools and GNU Make to streamlines builds. Gomk has built-in support for cross-compilation, `go fmt`, `go vet`, `golint`, `gocyclo`, `glide`, Travis-CI and Coveralls.io.
## Details

This talk will review the state of the Go build process and tool ecosystem as it exists today, outline similar solutions and why they fail to solve the underlying problem in a manner that is congruent with Go's native build tools, and then delve into the design of Gomk, how it works, and one or more working examples of Gomk in action.

Those in attendance, Go and DevOps engineers, will leave this talk with not only an understanding of how Gomk works and what problem it solves, but how to configure a meaningful, repeatable, and deterministic Go build process locally and on Travis-CI in five minutes or less.

**Comment by clintkitson** [comment]
LGTM
