### ISSUE TITLE
GnixUtils - Porting Common UNIX Commands to Go

### ISSUE THREAD

**Issue by akutz** [emccode/conferences#90]
## Type

Plenary
## Abstract

One of Go's strengths is that it's portable while yet another is the language's close ties to C. These two attributes make Go a natural choice to use as the means to create small, portable versions of common UNIX command-line utilities such as `cp`, `tar`, `sed`, `grep`, `env`, etc.

Come learn about [GnixUtils](https://github.com/akutz/gnixutils), dedicated to porting all of the common UNIX utilities, as well as several C stdlib libraries such as `getopt`, in oder to support systems administrators and software engineers alike.
## Details

This talk will review the necessity for portable, run-anywhere versions of the common UNIX command-line utilities such as `cp`, `tar`, `sed`, `grep`, `env`, etc. and explain why Go is the perfect language for providing the solution. Additionally, the details of how the commands and the C stdlib functions on which they depended were implemented will be discussed in detail.

Go engineers will want to attend in order to understand how GnixUtils is built and hopefully how they can contribute to it. Systems administrators will be interested to find out where they can download these utilities and just how close in parity said utils are to their native, UNIX counterparts.

**Comment by clintkitson** [comment]
I'll be at this one
