### ISSUE TITLE
State of the container eco-system with persistent applications

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#93]
First generation runtimes for containers assumed the workload inside the container would be stateless and ephemeral. But, most useful systems require storage of state somewhere. With the progression of container platforms from Mesos and Docker, you can easily run your stateful applications such as databases inside of containers. This session will cover the current state of persistent storage, containers and schedulers, including future directions in this arena.

**Comment by amandakatona** [comment]
I am not sure how I missed this before, but will you please submit this? We should join the first two sentences. Thanks! 

First generation runtimes for containers assumed the workload inside the container would be stateless and ephemeral, but most useful systems require storage of state somewhere. With the progression of container platforms from Mesos and Docker, you can easily run your stateful applications such as databases inside of containers. This session will cover the current state of persistent storage, containers and schedulers, including future directions in this arena.
