### ISSUE TITLE
Deep dive with Mesos and persistent storage for applications

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#94]
Persistent applications that can be complex to operate and scale tend to be perfect for Apache Mesos.  Internal direct attached storage and external storage are both options to run your applications.   This talk will outline patterns for using these to allow deployment of managed frameworks and tasks, while maintaining fault tolerance and scalability.

**Comment by davidvonthenen** [comment]
Submitted
https://github.com/dvonthenen/proposals/blob/master/2016_CONTAINERCAMP_US/DeepDiveWithMesosAndPersistentStorageForApps.md

**Comment by davidvonthenen** [comment]
Was rejected
