### ISSUE TITLE
Running stateful services on Cloud Native Platforms with Mesos

### ISSUE THREAD

**Issue by clintkitson** [emccode/conferences#95]
Many of today's PaaS systems are focused on stateless applications, scaling them from 1 to infinity and automatically rescheduling them when something goes wrong. But what about the data they create? How can we create scalable data persistence backends for our services to make sure our stored data is highly available?  In this session we will demonstrate stateless applications running on PaaS systems, connecting to data persistence layers like relational and NoSQL databases, all running on Mesos and all stored on highly available distributed storage platforms.

**Comment by ValentinFunk** [comment]
http://de.slideshare.net/EMCCODE/emc-world-2016-code16-running-stateful-services-on-cloud-native-platforms-with-mesos for anyone who stumbles across this on google
